#ifndef OFFSETS_H
#define OFFSETS_H

#define DW_LOCAL_PLAYER 0xDB75DC
#define DW_ENTITY_LIST 0x4DD344C
#define DW_CLIENT_STATE 0x58CFBC

#define M_hMY_WEAPONS 0x2E08

#define M_FL_FALL_BACK_WEAR 0x31E0
#define M_nFALL_BACK_PAINT_KIT 0x31D8
#define M_iITEM_DEFINITION_INDEX 0x2FBA
#define M_iITEM_ID_HIGH 0x2FD0

#endif